# Generated by Django 3.2.4 on 2021-06-18 07:57

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[images.models.validate_file_size]),
        ),
    ]
