# Generated by Django 3.2.4 on 2021-06-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_picture_image'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='picture',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='picture',
            name='slug',
        ),
    ]
